language: go
install:
- go get github.com/mattn/goveralls
- go get github.com/robfig/glock
- glock sync github.com/heketi/tests
matrix:
  include:
  - go: 1.2.2
    env: OPTIONS=""
  - go: 1.3.3
    env: OPTIONS="-race"
  - go: 1.4.2
    env: COVERAGE="true" GOTOOLS="yes"
  - go: 1.5
    env: OPTIONS="-race" GOTOOLS="yes"
before_script:
- if [[ "$GOTOOLS" = "yes" ]] ; then go get golang.org/x/tools/cmd/vet; fi
- if [[ "$GOTOOLS" = "yes" ]] ; then go get golang.org/x/tools/cmd/cover; fi
script:
- if [[ "$GOTOOLS" = "yes" ]] ; then go fmt ./... | wc -l | grep 0 ; fi
- if [[ "$GOTOOLS" = "yes" ]] ; then go vet ./... ; fi
- go test -v $OPTIONS ./...
- if [[ -n "$COVERAGE" ]]; then bash .travis-coverage; fi
